import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
const admin=(u:any)=>['admin','super_admin'].includes(u?.role);
Deno.serve(async(req)=>{try{const b=createClientFromRequest(req);const me=await b.auth.me().catch(()=>null);if(!admin(me))return Response.json({error:'Admin access required'},{status:403});const sr=b.asServiceRole;const x=await req.json().catch(()=>({}));const a=x.action||'dashboard';
if(a==='dashboard'){const [conversations,users,profiles,campaigns]=await Promise.all([sr.entities.CRMConversation.list('-last_message_at',300),sr.entities.User.list('-created_date',500),sr.entities.CRMUserProfile.list('-created_date',500).catch(()=>[]),sr.entities.CRMEmailCampaign.list('-created_date',100).catch(()=>[])]);return Response.json({conversations,users:users.map((u:any)=>({id:u.id,email:u.email,full_name:u.full_name,role:u.role,created_date:u.created_date})),profiles,campaigns});}
if(a==='messages'){const c=(await sr.entities.CRMConversation.filter({id:x.conversation_id}))[0];if(!c)return Response.json({error:'Conversation not found'},{status:404});const messages=await sr.entities.CRMMessage.filter({conversation_id:c.id},'created_date',500);await sr.entities.CRMConversation.update(c.id,{unread_by_admin:0});return Response.json({conversation:c,messages});}
if(a==='reply'){const c=(await sr.entities.CRMConversation.filter({id:x.conversation_id}))[0];if(!c)return Response.json({error:'Conversation not found'},{status:404});const body=String(x.body||'').trim().slice(0,4000);if(!body)return Response.json({error:'Reply required'},{status:400});await sr.entities.CRMMessage.create({conversation_id:c.id,owner_user_id:c.owner_user_id,sender_type:'admin',sender_user_id:me.id,sender_name:me.full_name||'BoriSend Support',sender_email:me.email||'',body,is_read_by_user:false,is_read_by_admin:true});await sr.entities.CRMConversation.update(c.id,{status:'waiting_on_user',last_message_at:new Date().toISOString(),last_message_preview:body.slice(0,180),unread_by_user:(c.unread_by_user||0)+1,unread_by_admin:0});if(!String(c.owner_user_id||'').startsWith('public:')&&!String(c.owner_user_id||'').startsWith('guest:')){await sr.entities.Notification.create({title:'BoriSend Support replied',body:`There is a new reply to: ${c.subject}`,type:'support_reply',priority:'normal',user_id:c.owner_user_id,created_by_id:c.owner_user_id}).catch(()=>{});}if(c.user_email){try{await sr.integrations.Core.SendEmail({to:c.user_email,subject:`Re: ${c.subject}`,body:`Hello${c.user_name?` ${c.user_name}`:''},\n\n${body}\n\nYou can continue this conversation from BoriSend Support.\n\nBoriSend`,from_name:'BoriSend'});}catch(e){console.warn('CRM reply email failed',e?.message);}}return Response.json({success:true});}
if(a==='status'){await sr.entities.CRMConversation.update(x.conversation_id,{status:x.status});return Response.json({success:true});}
if(a==='save_profile'){const old=await sr.entities.CRMUserProfile.filter({user_id:x.user_id});const data={user_id:x.user_id,tags:Array.isArray(x.tags)?x.tags:[],lifecycle_stage:x.lifecycle_stage||'active',admin_owner_user_id:x.admin_owner_user_id||'',next_follow_up_at:x.next_follow_up_at||null,last_contacted_at:x.last_contacted_at||null};const row=old[0]?await sr.entities.CRMUserProfile.update(old[0].id,data):await sr.entities.CRMUserProfile.create(data);return Response.json({profile:row});}
if(a==='add_note'){const note=String(x.note||'').trim().slice(0,4000);if(!note)return Response.json({error:'Note required'},{status:400});const row=await sr.entities.CRMContactNote.create({user_id:x.user_id,note,created_by_user_id:me.id});return Response.json({note:row});}
if(a==='notes'){return Response.json({notes:await sr.entities.CRMContactNote.filter({user_id:x.user_id},'-created_date',100)});}
return Response.json({error:'Unsupported action'},{status:400});}catch(e){console.error(e);return Response.json({error:e?.message||'CRM admin request failed'},{status:500});}});