import React,{useCallback,useEffect,useState} from "react";
import {base44} from "@/api/base44Client";
import PageLoader from "@/components/loaders/PageLoader";
import PageHeader from "@/components/layout/PageHeader";
import {Crown,Clock,PauseCircle,Check} from "lucide-react";
import {useTrialStatus} from "@/hooks/useTrialStatus";

export default function Subscription(){const[cap,setCap]=useState(null);const[config,setConfig]=useState(null);const[loading,setLoading]=useState(true);const{trialStatus}=useTrialStatus();const load=useCallback(async()=>{try{const[c,r]=await Promise.all([base44.entities.MembershipConfiguration.filter({is_active:true},"display_order",10),base44.functions.invoke("getCapacityStatus",{})]);setConfig(c?.[0]||null);setCap(r?.data||r);}catch{}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);if(loading)return <PageLoader/>;
return <div><PageHeader title="Membership Status" showHome/><div className="px-4 py-4 space-y-5">{trialStatus?.trial_active&&<section className="rounded-2xl bg-primary text-primary-foreground p-5"><div className="flex items-center gap-2 font-semibold"><Clock className="w-5 h-5"/>{trialStatus.trial_offer_name||"BoriSend Trial"}</div><p className="text-sm mt-2 opacity-80">{trialStatus.trial_days_remaining>1?`${trialStatus.trial_days_remaining} days remaining`:trialStatus.trial_is_last_day?"Ends today":`${trialStatus.trial_hours_remaining||0} hours remaining`}</p><p className="text-xs mt-3 opacity-70">Your account and saved information remain available if paid features pause after the trial.</p></section>}{trialStatus?.is_paused&&<section className="rounded-2xl bg-destructive text-destructive-foreground p-5"><div className="flex items-center gap-2 font-semibold"><PauseCircle className="w-5 h-5"/>Paid features paused</div><p className="text-sm mt-2 opacity-80">This account does not currently have active paid access. Your account and saved information remain available.</p></section>}<section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2 mb-4"><Crown className="w-5 h-5 text-primary"/><h2 className="font-semibold">{config?.display_name||"BoriSend Membership"}</h2>{["active","grace"].includes(cap?.membershipStatus)&&<span className="ml-auto text-xs border rounded-full px-2 py-1">Active</span>}</div><div className="space-y-4">{cap?.plan&&<Row label="Communication Plans" c={cap.plan}/>} {cap?.recipient&&<Row label="Recipient Units" c={cap.recipient}/>} {cap?.message&&<Row label="Generated Messages" c={cap.message}/>} {cap?.message_pass&&<Row label="Message Passes" c={cap.message_pass}/>} {cap?.smart_message&&<Row label="Smart Messages" c={cap.smart_message}/>}</div></section>{cap?.addons?.length>0&&<section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold mb-3">Active capacity add-ons</h2><div className="space-y-2">{cap.addons.map(a=><div key={a.id} className="border rounded-xl p-3 flex justify-between gap-3"><div><p className="text-sm font-medium">Additional capacity</p><p className="text-xs text-muted-foreground capitalize">{String(a.entitlement_type||"").replaceAll("_"," ")}</p></div><Check className="w-4 h-4 text-primary"/></div>)}</div></section>}<p className="text-xs text-center text-muted-foreground px-4">This app displays membership and capacity status only. It does not offer purchasing or billing management.</p></div></div>}
function Row({label,c}){const unlimited=c.effective>=999999;return <div><div className="flex justify-between text-xs mb-1.5"><span className="text-muted-foreground">{label}</span><span className="font-semibold">{unlimited?`${c.used} / ∞`:`${c.used} of ${c.effective}`}</span></div>{!unlimited&&<div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary rounded-full" style={{width:`${c.effective>0?Math.min(100,(c.used/c.effective)*100):100}%`}}/></div>}</div>}
