/**
 * Strategy Library — Deterministic relationship strategy rules.
 * Provider-neutral and portable — no Base44 dependencies.
 *
 * Architecture: reusable base strategies per relationship family, layered with
 * state overrides and goal overrides. This avoids asking the LLM to invent
 * strategy rules every time (§5, §31). The strategy engine merges:
 *   base → state override → goal override → safety adjustment.
 *
 * Do not hard-code exact message wording — strategies describe principles and
 * behaviours, not final text.
 */

import type { RelationshipStrategy, RecommendedFrequencyRange } from './types.ts';

// ── Reusable frequency presets ──
const FREQ_FREQUENT: RecommendedFrequencyRange = { min_per_week: 5, max_per_week: 7, description: 'Frequent, near-daily contact' };
const FREQ_REGULAR: RecommendedFrequencyRange = { min_per_week: 3, max_per_week: 5, description: 'Regular contact several times a week' };
const FREQ_PERIODIC: RecommendedFrequencyRange = { min_per_week: 1, max_per_week: 3, description: 'Periodic contact a few times a week' };
const FREQ_LOW_PRESSURE: RecommendedFrequencyRange = { min_per_week: 1, max_per_week: 2, description: 'Low-pressure periodic contact' };
const FREQ_EVENT_DRIVEN: RecommendedFrequencyRange = { min_per_week: 0, max_per_week: 2, description: 'Event-driven or occasional contact' };

// ── Base strategies per relationship family ──
export const BASE_STRATEGIES: Record<string, RelationshipStrategy> = {
  romantic_marital: {
    strategy_key: 'romantic_marital_base',
    objective: 'Nurture warmth, appreciation, and emotional closeness with a romantic partner or spouse.',
    principles: ['warm', 'affectionate', 'genuine', 'appreciative', 'consistent'],
    encouraged_behaviours: ['express appreciation regularly', 'recall shared memories', 'celebrate milestones', 'use pet names where natural'],
    avoid_behaviours: ['generic compliments', 'repetitive phrasing', 'sounding transactional'],
    recommended_tone: 'loving',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_FREQUENT,
    allowed_message_intents: ['check_in', 'appreciation', 'encouragement', 'gratitude', 'celebration', 'shared_memory', 'milestone', 'congratulations', 'thoughtful_question', 'relationship_maintenance'],
    disallowed_message_intents: ['client_check_in', 'development_support', 'pastoral_encouragement'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  parent_child: {
    strategy_key: 'parent_child_base',
    objective: 'Maintain a caring, supportive connection with a child appropriate to their age and autonomy.',
    principles: ['warm', 'supportive', 'genuine interest', 'age-appropriate', 'respect autonomy'],
    encouraged_behaviours: ['show genuine interest in their life', 'encourage their efforts', 'celebrate milestones', 'offer support without pressure'],
    avoid_behaviours: ['guilt-tripping', 'demanding replies', 'lecturing', 'comparing to others'],
    recommended_tone: 'warm',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_REGULAR,
    allowed_message_intents: ['check_in', 'encouragement', 'celebration', 'milestone', 'congratulations', 'thoughtful_question', 'shared_memory', 'practical_support', 'gentle_reconnection'],
    disallowed_message_intents: ['client_check_in', 'pastoral_encouragement', 'recognition'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  family_extended: {
    strategy_key: 'family_extended_base',
    objective: 'Keep extended family connections warm and consistent.',
    principles: ['warm', 'inclusive', 'genuine', 'respectful'],
    encouraged_behaviours: ['remember important family moments', 'show genuine interest', 'stay in touch regularly'],
    avoid_behaviours: ['family politics', 'guilt', 'comparing family members'],
    recommended_tone: 'warm',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_PERIODIC,
    allowed_message_intents: ['check_in', 'appreciation', 'celebration', 'shared_memory', 'milestone', 'thoughtful_question', 'relationship_maintenance'],
    disallowed_message_intents: ['client_check_in', 'pastoral_encouragement'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  friendship_personal: {
    strategy_key: 'friendship_personal_base',
    objective: 'Maintain a genuine, supportive friendship with consistent and natural contact.',
    principles: ['friendly', 'genuine', 'supportive', 'low-pressure'],
    encouraged_behaviours: ['show genuine interest', 'recall shared experiences', 'celebrate their wins', 'be present in tough times'],
    avoid_behaviours: ['forced contact', 'sounding transactional', 'over-familiarity too soon in new friendships'],
    recommended_tone: 'friendly',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_REGULAR,
    allowed_message_intents: ['check_in', 'appreciation', 'encouragement', 'gratitude', 'celebration', 'shared_memory', 'thoughtful_question', 'relationship_maintenance', 'gentle_reconnection'],
    disallowed_message_intents: ['client_check_in', 'pastoral_encouragement', 'development_support'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  workplace_professional: {
    strategy_key: 'workplace_professional_base',
    objective: 'Strengthen a professional working relationship with appropriate warmth and boundaries.',
    principles: ['professional', 'respectful', 'encouraging', 'boundaried'],
    encouraged_behaviours: ['recognise specific contributions', 'offer professional encouragement', 'acknowledge milestones', 'check in on wellbeing appropriately'],
    avoid_behaviours: ['excessive personal familiarity', 'coercive authority-based language', 'overstepping professional boundaries', 'romantic undertones'],
    recommended_tone: 'professional',
    communication_boundary_notes: ['Maintain professional boundaries — no romantic or overly personal language.'],
    recommended_frequency_range: FREQ_PERIODIC,
    allowed_message_intents: ['check_in', 'recognition', 'encouragement', 'appreciation', 'development_support', 'milestone', 'congratulations', 'thoughtful_question'],
    disallowed_message_intents: ['gratitude', 'shared_memory', 'gentle_reconnection', 'pastoral_encouragement', 'client_check_in'],
    escalation_notes: '',
    de_escalation_notes: 'If a boundary feels crossed, return to purely professional recognition.',
    safety_status: 'SAFE',
  },
  business_customer: {
    strategy_key: 'business_customer_base',
    objective: 'Maintain a valued client or customer relationship through genuine, value-led communication.',
    principles: ['professional', 'value-led', 'genuine interest', 'respectful of their time'],
    encouraged_behaviours: ['show genuine interest in their situation', 'provide value before pitching', 'appreciate their business', 'acknowledge milestones'],
    avoid_behaviours: ['immediate hard selling', 'spam frequency', 'sales pressure in reconnection', 'generic marketing language'],
    recommended_tone: 'professional',
    communication_boundary_notes: ['Reconnect before pitching. Do not lead with a sale after a gap.'],
    recommended_frequency_range: FREQ_EVENT_DRIVEN,
    allowed_message_intents: ['client_check_in', 'appreciation', 'gratitude', 'celebration', 'milestone', 'relationship_maintenance', 'thoughtful_question'],
    disallowed_message_intents: ['encouragement', 'shared_memory', 'pastoral_encouragement', 'development_support', 'gentle_reconnection'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  faith_spiritual: {
    strategy_key: 'faith_spiritual_base',
    objective: 'Provide pastoral encouragement and care with a respectful, supportive spiritual tone.',
    principles: ['caring', 'encouraging', 'respectful', 'faith-sensitive'],
    encouraged_behaviours: ['offer encouragement', 'recognise important moments', 'show genuine care', 'respectful spiritual tone'],
    avoid_behaviours: ['spiritual manipulation', 'guilt', 'pressure', 'claiming divine certainty', 'creating inappropriate dependency', 'misuse of pastoral authority'],
    recommended_tone: 'pastoral',
    communication_boundary_notes: ['Avoid claiming divine certainty or spiritual manipulation. Never pressure or induce guilt.'],
    recommended_frequency_range: FREQ_PERIODIC,
    allowed_message_intents: ['pastoral_encouragement', 'check_in', 'encouragement', 'celebration', 'milestone', 'shared_memory', 'thoughtful_question'],
    disallowed_message_intents: ['recognition', 'development_support', 'client_check_in'],
    escalation_notes: '',
    de_escalation_notes: 'If a member seems overwhelmed, reduce frequency and keep messages simple and caring.',
    safety_status: 'SAFE',
  },
  community_social: {
    strategy_key: 'community_social_base',
    objective: 'Foster a sense of belonging and connection within a community or social group.',
    principles: ['inclusive', 'warm', 'encouraging', 'respectful'],
    encouraged_behaviours: ['welcome members', 'acknowledge contributions', 'share community moments', 'encourage participation'],
    avoid_behaviours: ['exclusionary language', 'pressure to participate', 'political or divisive content'],
    recommended_tone: 'friendly',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_PERIODIC,
    allowed_message_intents: ['check_in', 'appreciation', 'encouragement', 'celebration', 'relationship_maintenance', 'thoughtful_question'],
    disallowed_message_intents: ['pastoral_encouragement', 'development_support', 'client_check_in'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  education_development: {
    strategy_key: 'education_development_base',
    objective: 'Support a learner or coachee with encouragement, development guidance, and recognition.',
    principles: ['encouraging', 'patient', 'constructive', 'growth-oriented'],
    encouraged_behaviours: ['encourage progress', 'recognise milestones', 'offer constructive support', 'show genuine interest in development'],
    avoid_behaviours: ['discouragement', 'condescension', 'overwhelming with advice', 'pressure'],
    recommended_tone: 'encouraging',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_PERIODIC,
    allowed_message_intents: ['encouragement', 'development_support', 'recognition', 'celebration', 'milestone', 'thoughtful_question', 'check_in'],
    disallowed_message_intents: ['gratitude', 'shared_memory', 'gentle_reconnection', 'client_check_in'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  care_support: {
    strategy_key: 'care_support_base',
    objective: 'Provide caring, supportive communication to someone receiving care or support.',
    principles: ['caring', 'gentle', 'patient', 'non-demanding', 'respectful'],
    encouraged_behaviours: ['check in gently', 'offer encouragement', 'show genuine care', 'respect their pace and capacity'],
    avoid_behaviours: ['pressure to respond', 'minimising their situation', 'over-familiarity', 'clinical language'],
    recommended_tone: 'encouraging',
    communication_boundary_notes: ['Do not pressure responses. Respect their capacity. This is not professional counselling.'],
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    allowed_message_intents: ['check_in', 'encouragement', 'practical_support', 'thoughtful_question', 'appreciation', 'celebration'],
    disallowed_message_intents: ['client_check_in', 'recognition', 'development_support', 'pastoral_encouragement'],
    escalation_notes: '',
    de_escalation_notes: 'If the person seems overwhelmed, reduce frequency and keep messages very simple.',
    safety_status: 'SAFE',
  },
  membership_organisation: {
    strategy_key: 'membership_organisation_base',
    objective: 'Maintain engagement and appreciation for members or supporters of an organisation.',
    principles: ['appreciative', 'informative', 'inclusive', 'respectful'],
    encouraged_behaviours: ['show appreciation for membership', 'acknowledge milestones', 'keep members informed of relevant moments'],
    avoid_behaviours: ['over-communication', 'pressure', 'generic mass-messaging tone'],
    recommended_tone: 'appreciative',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_EVENT_DRIVEN,
    allowed_message_intents: ['check_in', 'appreciation', 'celebration', 'milestone', 'relationship_maintenance'],
    disallowed_message_intents: ['pastoral_encouragement', 'development_support', 'gentle_reconnection'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
  network_influence: {
    strategy_key: 'network_influence_base',
    objective: 'Maintain professional network connections with genuine, low-pressure contact.',
    principles: ['professional', 'genuine', 'low-pressure', 'respectful of time'],
    encouraged_behaviours: ['genuine check-ins', 'acknowledge professional milestones', 'show appreciation', 'stay loosely connected'],
    avoid_behaviours: ['transactional networking tone', 'sales pressure', 'over-familiarity', 'demanding responses'],
    recommended_tone: 'professional',
    communication_boundary_notes: [],
    recommended_frequency_range: FREQ_EVENT_DRIVEN,
    allowed_message_intents: ['check_in', 'appreciation', 'relationship_maintenance', 'thoughtful_question', 'shared_memory'],
    disallowed_message_intents: ['pastoral_encouragement', 'development_support', 'gentle_reconnection', 'recognition'],
    escalation_notes: '',
    de_escalation_notes: '',
    safety_status: 'SAFE',
  },
};

// ── State overrides (applied on top of base) ──
export const STATE_OVERRIDES: Record<string, Partial<RelationshipStrategy>> = {
  new: {
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    communication_boundary_notes: ['New relationship — keep contact gentle and avoid overwhelming.'],
    de_escalation_notes: 'Slow down if the recipient seems unresponsive; allow space.',
  },
  neglected: {
    strategy_key: '_neglected',
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    communication_boundary_notes: ['Gentle re-entry — do not lead with demands or guilt about the gap.'],
    encouraged_behaviours: ['genuine, no-pressure re-entry', 'acknowledge the gap subtly without guilt', 'show you still care'],
    avoid_behaviours: ['guilt about lack of contact', 'demanding immediate response', 'pretending no time has passed'],
  },
  distant: {
    strategy_key: '_distant',
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    principles: ['warm', 'non-demanding', 'patient', 'gradual reconnection', 'allow space'],
    encouraged_behaviours: ['warm, non-demanding contact', 'genuine interest', 'gradual reconnection', 'allow space'],
    avoid_behaviours: ['guilt', 'blame', 'repeated references to lack of contact', 'demanding replies', 'excessive frequency'],
    communication_boundary_notes: ['Low-pressure periodic contact — allow the recipient space. Do not demand replies or reference the gap with guilt.'],
    de_escalation_notes: 'If the recipient does not respond, do not escalate frequency. Allow space.',
    allowed_message_intents: ['gentle_reconnection', 'check_in', 'shared_memory', 'thoughtful_question', 'celebration'],
  },
  strained: {
    strategy_key: '_strained',
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    safety_status: 'CAUTION',
    safety_reason: 'Relationship is strained — communication should be gentle and non-pressuring.',
    communication_boundary_notes: ['Strained relationship — avoid sensitive topics, blame, and pressure. Consider explicit boundaries before communication.'],
    avoid_behaviours: ['blame', 'revisiting conflict', 'pressure', 'demanding responses', 'guilt'],
    de_escalation_notes: 'Prioritise de-escalation. Keep messages short, warm, and free of conflict references.',
  },
  rebuilding: {
    strategy_key: '_rebuilding',
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    principles: ['patient', 'gradual', 'consistent', 'non-pressuring', 'trust-building'],
    communication_boundary_notes: ['Rebuilding phase — gradual, patient contact. Do not rush or pressure.'],
    avoid_behaviours: ['rushing reconciliation', 'demanding trust', 'revisiting past conflict', 'pressure'],
    de_escalation_notes: 'Trust rebuilds slowly. Prioritise consistency over intensity.',
  },
};

// ── Goal overrides (applied on top of base + state) ──
export const GOAL_OVERRIDES: Record<string, Partial<RelationshipStrategy>> = {
  reconnect: {
    strategy_key: '_reconnect',
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    objective: 'Reconnect gently after a period of distance — low-pressure, genuine re-entry.',
    principles: ['warm', 'non-demanding', 'patient', 'genuine interest', 'gradual reconnection', 'allow space'],
    encouraged_behaviours: ['genuine, no-pressure re-entry', 'reconnect before asking for anything', 'show you still care'],
    avoid_behaviours: ['guilt', 'blame', 'repeated references to lack of contact', 'demanding replies', 'excessive frequency', 'immediate asks'],
    communication_boundary_notes: ['Reconnect before pitching or asking. Low-pressure periodic contact.'],
    allowed_message_intents: ['gentle_reconnection', 'check_in', 'shared_memory', 'thoughtful_question', 'celebration'],
  },
  rebuild_trust_gradually: {
    strategy_key: '_rebuild_trust',
    recommended_frequency_range: FREQ_LOW_PRESSURE,
    objective: 'Rebuild trust gradually through consistent, patient, non-pressuring contact.',
    principles: ['patient', 'consistent', 'genuine', 'non-pressuring', 'trust-building'],
    encouraged_behaviours: ['consistent low-pressure contact', 'acknowledge without re-litigating', 'show reliability over time'],
    avoid_behaviours: ['rushing reconciliation', 'demanding trust', 'revisiting past conflict', 'pressure', 'guilt'],
    de_escalation_notes: 'Trust rebuilds slowly. Consistency over intensity.',
  },
  recognise_contribution: {
    strategy_key: '_recognise',
    objective: 'Recognise a specific contribution with professional warmth and encouragement.',
    encouraged_behaviours: ['specific recognition of what they did', 'professional warmth', 'encouragement', 'development support'],
    allowed_message_intents: ['recognition', 'appreciation', 'encouragement', 'development_support', 'milestone', 'congratulations'],
    recommended_tone: 'appreciative',
  },
  maintain_client_relationship: {
    strategy_key: '_maintain_client',
    objective: 'Maintain or re-establish a client relationship through value-led, professional communication.',
    principles: ['professional', 'value-led', 'genuine interest', 'reconnect before pitching'],
    encouraged_behaviours: ['professional re-entry', 'genuine interest', 'value-led communication', 'appreciation'],
    avoid_behaviours: ['immediate hard selling', 'spam frequency', 'sales pressure', 'generic marketing'],
    communication_boundary_notes: ['Reconnect before pitching. Do not lead with a sale.'],
    allowed_message_intents: ['client_check_in', 'appreciation', 'relationship_maintenance', 'thoughtful_question', 'milestone'],
    recommended_tone: 'professional',
  },
  provide_pastoral_encouragement: {
    strategy_key: '_pastoral',
    objective: 'Provide pastoral encouragement and care with a respectful, supportive spiritual tone.',
    encouraged_behaviours: ['encouragement', 'care', 'recognition of important moments', 'respectful spiritual tone', 'supportive check-ins'],
    avoid_behaviours: ['spiritual manipulation', 'guilt', 'pressure', 'claiming divine certainty', 'inappropriate dependency', 'misuse of pastoral authority'],
    communication_boundary_notes: ['No spiritual manipulation, guilt, or pressure. Never claim divine certainty.'],
    allowed_message_intents: ['pastoral_encouragement', 'encouragement', 'check_in', 'celebration', 'milestone'],
    recommended_tone: 'pastoral',
  },
  improve_employee_engagement: {
    strategy_key: '_employee_engagement',
    objective: 'Improve employee engagement through recognition, encouragement, and appropriate wellbeing support.',
    encouraged_behaviours: ['specific recognition', 'professional warmth', 'encouragement', 'development support', 'appropriate wellbeing check-ins', 'acknowledgement of milestones'],
    avoid_behaviours: ['excessive personal familiarity', 'coercive authority-based language', 'overstepping professional boundaries'],
    allowed_message_intents: ['recognition', 'encouragement', 'appreciation', 'development_support', 'check_in', 'milestone', 'congratulations'],
  },
  mentor_develop: {
    strategy_key: '_mentor',
    objective: 'Mentor and develop through encouragement, constructive guidance, and recognition of progress.',
    encouraged_behaviours: ['encourage progress', 'recognise milestones', 'offer constructive guidance', 'show genuine interest in development'],
    allowed_message_intents: ['development_support', 'encouragement', 'recognition', 'celebration', 'milestone', 'thoughtful_question'],
  },
  celebrate_important_moments: {
    strategy_key: '_celebrate',
    objective: 'Celebrate an important moment, milestone, or occasion genuinely.',
    allowed_message_intents: ['celebration', 'milestone', 'congratulations', 'appreciation'],
    encouraged_behaviours: ['genuine celebration', 'specific acknowledgement of the moment'],
  },
};

// Safe fallback strategy for unknown/legacy categories
export const SAFE_FALLBACK_STRATEGY: RelationshipStrategy = {
  strategy_key: 'safe_fallback',
  objective: 'Maintain a warm, genuine connection.',
  principles: ['warm', 'genuine', 'low-pressure', 'respectful'],
  encouraged_behaviours: ['show genuine interest', 'be consistent', 'be warm'],
  avoid_behaviours: ['pressure', 'guilt', 'generic language', 'sounding transactional'],
  recommended_tone: 'warm',
  communication_boundary_notes: [],
  recommended_frequency_range: FREQ_PERIODIC,
  allowed_message_intents: ['check_in', 'appreciation', 'encouragement', 'celebration', 'shared_memory', 'thoughtful_question', 'relationship_maintenance'],
  disallowed_message_intents: [],
  escalation_notes: '',
  de_escalation_notes: '',
  safety_status: 'SAFE',
};